apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-httpbin.fullname" . }}
  labels:
    {{- include "go-httpbin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  ports:
  - name: http
    port: {{ .Values.service.ports.http.port }}
    targetPort: {{ .Values.service.ports.http.targetPort }}
    protocol: {{ .Values.service.ports.http.protocol }}
  - name: https
    port: {{ .Values.service.ports.https.port }}
    targetPort: {{ .Values.service.ports.https.targetPort }}
    protocol: {{ .Values.service.ports.https.protocol }}
  - name: quic
    port: {{ .Values.service.ports.quic.port }}
    targetPort: {{ .Values.service.ports.quic.targetPort }}
    protocol: {{ .Values.service.ports.quic.protocol }}
  selector:
    {{- include "go-httpbin.selectorLabels" . | nindent 4 }}
